from typing import Protocol


class SensorProtocol(Protocol):
    def read(self) -> tuple[float, float]:
        """Return (distance_cm, temperature_c)."""
        ...


class PumpProtocol(Protocol):
    def set_angle(self, angle: int) -> None: ...
    def get_angle(self) -> int: ...
    def get_dispensed(self) -> float: ...


class MotorProtocol(Protocol):
    def move_to(self, target_cm: float) -> None: ...
    def get_position(self) -> float: ...
    def stop(self) -> None: ...
    def is_moving(self) -> bool: ...
